{{- if not .Values.mcm.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: rancher.cattle.io
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: {{ .Values.caBundle }}
    service:
      name: rancher-webhook
      namespace: cattle-system
      path: /v1/webhook/validation/features.management.cattle.io
      port: 443
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: rancher.cattle.io.features.management.cattle.io
  rules:
  - apiGroups:
    - management.cattle.io
    apiVersions:
    - v3
    operations:
    - UPDATE
    resources:
    - features
    scope: Cluster
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: {{ .Values.caBundle }}
    service:
      name: rancher-webhook
      namespace: cattle-system
      path: /v1/webhook/validation/clusters.management.cattle.io
      port: 443
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: rancher.cattle.io.clusters.management.cattle.io
  rules:
  - apiGroups:
    - management.cattle.io
    apiVersions:
    - v3
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - clusters
    scope: Cluster
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: {{ .Values.caBundle }}
    service:
      name: rancher-webhook
      namespace: cattle-system
      path: /v1/webhook/validation/rke-machine-config.cattle.io
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: rancher.cattle.io.rke-machine-config.cattle.io
  rules:
  - apiGroups:
    - rke-machine-config.cattle.io
    apiVersions:
    - v1
    operations:
    - UPDATE
    resources:
    - '*'
    scope: Namespaced
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: {{ .Values.caBundle }}
    service:
      name: rancher-webhook
      namespace: cattle-system
      path: /v1/webhook/validation/namespaces
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: rancher.cattle.io.namespaces.delete-namespace
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values:
      - fleet-local
      - local
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - DELETE
    resources:
    - namespaces
    scope: Cluster
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: {{ .Values.caBundle }}
    service:
      name: rancher-webhook
      namespace: cattle-system
      path: /v1/webhook/validation/namespaces
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: rancher.cattle.io.namespaces
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - UPDATE
    resources:
    - namespaces
    scope: Cluster
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: {{ .Values.caBundle }}
    service:
      name: rancher-webhook
      namespace: cattle-system
      path: /v1/webhook/validation/namespaces
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: rancher.cattle.io.namespaces.create-non-kubesystem
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - namespaces
    scope: Cluster
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: {{ .Values.caBundle }}
    service:
      name: rancher-webhook
      namespace: cattle-system
      path: /v1/webhook/validation/namespaces
      port: 443
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: rancher.cattle.io.namespaces.create-kubesystem-only
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values:
      - kube-system
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - namespaces
    scope: Cluster
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: {{ .Values.caBundle }}
    service:
      name: rancher-webhook
      namespace: cattle-system
      path: /v1/webhook/validation/clusterrepos.catalog.cattle.io
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: rancher.cattle.io.clusterrepos.catalog.cattle.io
  rules:
  - apiGroups:
    - catalog.cattle.io
    apiVersions:
    - v1
    operations:
    - UPDATE
    - CREATE
    resources:
    - clusterrepos
    scope: Namespaced
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: {{ .Values.caBundle }}
    service:
      name: rancher-webhook
      namespace: cattle-system
      path: /v1/webhook/validation/auditpolicies.auditlog.cattle.io
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: rancher.cattle.io.auditpolicies.auditlog.cattle.io
  rules:
  - apiGroups:
    - auditlog.cattle.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - auditpolicies
    scope: Cluster
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: {{ .Values.caBundle }}
    service:
      name: rancher-webhook
      namespace: cattle-system
      path: /v1/webhook/validation/clusterauthtokens.cluster.cattle.io
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: rancher.cattle.io.clusterauthtokens.cluster.cattle.io
  rules:
  - apiGroups:
    - cluster.cattle.io
    apiVersions:
    - v3
    operations:
    - UPDATE
    - CREATE
    resources:
    - clusterauthtokens
    scope: Namespaced
  sideEffects: None
{{- end }}
