name: Test stuff

on:
  workflow_dispatch:
    inputs:
      charts_ref:
        description: "Version of rancher/rancher to compare"
        required: true
        default: "main"

env:
  CHARTS_REF: "${{ github.event.inputs.charts_ref }}"

permissions:
  contents: write

jobs:
  sync:
    name: Sync dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout charts repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: ${{ github.repository_owner }}/rancher-charts
          ref: "${{ env.CHARTS_REF }}"
          token: "${{ secrets.MY_SECRET }}"
          path: charts
          # Allow making git push request later on
          persist-credentials: true

      - name: Run release script
        run: |
          cd charts
          BRANCH="bump-webhook-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}"
          echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
          git checkout -b "$BRANCH" "$CHARTS_REF"
          git push origin "$BRANCH"
